---
sudo: required
# docker is required to run tests
services: docker

install:
  - bundle install

script:
  # run kitchen tests (destroy, create, converge, setup, verify and destroy)
  - kitchen test

notifications:
  slack:
    secure: opYFN+x7SHPhWD3nvp1YViwHeC4b5T5KBiP6bEcoo4cYmlwn4wDaPWW7M90Jo6ISIa1+Sq5QSR/uppvM1asjjACoCjVl+gAud9S6uJY8FjMxJ2ZrI4osC6wLJJOVHwyqzdlxc4YOXnpsLxo4T/kssgHv0gET0wRyEu51lQt5bl7hSeyaKSNmuDDLgYpwwQtDlHzBF0R0wqJR5P4FyiBAgV6JJ9uZAVzIx29GRR+r8kAg+v7bKLdouEnuRGRpuNPm/3c0aKc1rotXF2SlssokYNcl4gDwr4NHo5WXyDdUwhZHa1WONmQy0FnzC+qdjJ2iRdiKEWqJDBqmWvELlTekoomHmJ57Att6mGreYWrzv8KqJMIGKRJWu3x4l9ZlMFy04eU/nVL/QVhb3uauB5/5R3AtzNerTDLVE/ra81fQmZSQwIlPVKyC7VquXuXwroVOll6DXU5bL3mY3Jqf8a9Oc5zXqQDg5z3dAob3V9kFcvj+0ceGJ9YK1f5kqxBJZFM30mgAkn6iUPOkdJ2NHwKsVNKA1qpB+hwi850lle8y2iNTNNSWKrxB8AQPJ2dRJmQpSF9q70N5AdCth70H7P9mQC9qxuCU+xk+cnB8YfTM+sN17npWDLvKD13UUyEcYdlZxLSA8I9AAE/wSAqF2WpeO26eCoBLqic/VmttIPZuQ8o=
